let  tool=require("./index.js");
tool.trim(" a  b  c  d  1  2 3 ","type");
tool.changeCase("HbcSKLKoWD","word");
tool.repeatStr("abc",2);
tool.replaceAll("这里是上海,中国第三大城市,上海省省会,简称穗","上海","广州");
tool.replaceStrr("1asd88465asdwqe3",5,1,"+");
tool.checkType("0352-6822633","tel");
tool.checkPwd('12aseefd');
tool.randomWord(36);
tool.strSplit("sad44654blog5a1sd67as9dablog4s5d16zxc4sdweasjkblogwqepaskdkblogahseiuadbhjcibloguyeajzxkcabloguyiwezxc967","blog");
tool.formatText("1234asda567asd890","4","-");
tool.titleCaseUp("this is a title");
tool.longestWord("Find the Longest word in a String");